### ISSUE TITLE
Ability to modify flow lines while being drawn/determine points along flow lines

### ISSUE THREAD

**Issue by jcquinlan** [acamposuribe/p5.brush#18]
Not sure if you're taking any sort of feature requests (and recognizing that this project is open source I should really just be taking it upon myself to work on solving this problem), but it would be amazing to be able to either modify flow lines as they are being drawn (perhaps a callback with the ability to intercept each segment of the line), and/or deterministically get coordinates along a flow line easily.

Apologies if the ability to do either of this things is already present in the library, or if there is math Im unaware of afford the latter idea.

Absolutely loving the library so far, excited for it's future and hopefully contributing at some point!

**Comment by acamposuribe** [comment]
Hey @jcquinlan 

I don't know if I'm understanding your message correctly, but I think you might be able to do just what you need with the Position class: https://github.com/acamposuribe/p5.brush?tab=readme-ov-file#exposed-classes

The Position class lets you create a new coordinates object with `new brush.Position(x,y)`, which you can then move through the flowfield, whatever distance you want. This is equivalent to how flowlines are drawn. The only thing is that if you want to move exactly following a flowline, you need to know the step_length for that specific brush type.

You can use the brush.Position class like this:

`
// Let's set the HB 
brush.set("HB", "black", 1)

// Let's draw a "horizontal" 0 degrees flowline starting at (10,30), of 100px length
brush.flowLine(10, 30, 100, 0)

// Let's say we want to find the coordinates in these path, every 10px
let coordinates = []

// We create a Position object in the starting coordinates
let pos = new brush.Position(10,30)

// We move 10px through the 0 degrees path
// It's important to notice that this movement is cumulative, that is,
// once the position has been moved, its coordinates are updated
for (let i = 0; i < 10; i++) {
   pos.moveTo(10, 0)
   coordinates.push([pos.x, pos.y])
}

// This are the 10 points through the flow path
console.log(coordinates)
`

I hope this helps!
(I'm pushing a small change to the code in order to make this work better, since I just found a small problem)

**Comment by acamposuribe** [comment]
In any case, if what you want to do is draw a series of segments with different sizes and different directions, it's probably much easier to use the Plot class, that lets you create just that!
To be honest, the documentation for the three exposed classes is very minimal, but these are basically the core of the whole library. If you learn to use them, you can do almost everything

**Comment by jcquinlan** [comment]
Circling back on this to say A.) thanks for pointing me in the right direction, as the Position class indeed allowed me to do what I was thinking originally, and B.) apologize for not having more thoroughly explored the docs before creating an issue!

I'll close the issue now, thanks for all your hard work!
